apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    filebeat_enable: "true"
  labels:
    io.kompose.service: order-service
  name: order-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        filebeat_enable: "true"
      labels:
        io.kompose.service: order-service
        filebeat_enable: "true"
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
          # 必须加80, 见我的笔记 - containerd 设置使用http访问harbor
          image: harbor.local:80/library/order-service:latest
          imagePullPolicy: IfNotPresent
          name: order-service
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 512Mi
      restartPolicy: Always
