apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: order-service
  name: order-service
  namespace: apps
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

  selector:
    k8s-app: order-service
