apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
    spec:
      containers:
        - env:
            - name: ES_JAVA_OPTS
              value: -Xms2g -Xmx4g
            - name: discovery.type
              value: single-node
            - name: ingest.geoip.downloader.enabled
              value: "false"
            - name: xpack.security.enabled
              value: "false"
          image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
      hostname: elasticsearch
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
