apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  namespace: logging
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
  selector:
    k8s-app: elasticsearch
