apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: es-data
  name: es-data
  namespace: logging
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
