apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kibana
  name: kibana
  namespace: logging
spec:
  ports:
    - name: "5601"
      port: 5601
      targetPort: 5601
  selector:
    k8s-app: kibana
