apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: logstash
  name: logstash
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        k8s-app: logstash
    spec:
      containers:
        - env:
            - name: LS_JAVA_OPTS
              value: -Xms512m -Xmx1g
          image: docker.elastic.co/logstash/logstash:8.17.4
          name: logstash
          ports:
            - containerPort: 5044
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline
              name: logstash-cm0
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstash-cm1
              readOnly: true
              subPath: logstash.yml
      restartPolicy: Always
      volumes:
        - configMap:
            name: logstash-cm0
          name: logstash-cm0
        - configMap:
            items:
              - key: logstash.yml
                path: logstash.yml
            name: logstash-cm1
          name: logstash-cm1
