apiVersion: v1
data:
  logstash.conf: |-
    input {
      beats {
        port => 5044
        codec => "plain"   # 先按纯文本读，不强行解析
      }
    }

    
    filter {
      # 在所有处理前打印完整事件结构（调试用）
      ruby {
        code => "
          puts '[DEBUG] === BEFORE FILTER ==='
          puts event.to_hash.inspect
          puts '[DEBUG] ====================='
        "
      }
    
        # 保留需要的：提取字段、打标签、清理冗余
      if [appname] == "demo-elk" {
        mutate {
          add_tag => ["parsed-success"]
          remove_field => [
            "agent", "input", "host", "ecs", "log", "stream",
            "event.original", "source", "prospector"
          ]
        }
      }
    
      # 对齐时间(已经在spring boot/filebeat里处理了)
      #date {
      #  match => [ "timestamp", "ISO8601" ]
      #  target => "@timestamp"
      #}
        
    }


    output {
      #stdout { codec => rubydebug }

      if "parsed-success" in [tags] {
        elasticsearch {
          hosts => ["http://elasticsearch:9200"]
          index => "app-logs-%{+YYYY.MM.dd}"
          document_type => "_doc"
          template_overwrite => true
        }
      }

    }
kind: ConfigMap
metadata:
  labels:
    k8s-app: logstash
  name: logstash-cm0
  namespace: logging