apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: logstash
  name: logstash
  namespace: logging
spec:
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
  selector:
    k8s-app: logstash
