apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.inputs:
      # 采集
      - type: container
        paths:
          - /var/log/containers/*.log    # 符号链接
          - /var/log/pods/*/*/*.log      # 实际日志文件
        processors:
          # 标注
          - add_kubernetes_metadata:
              host: ${NODE_NAME}
              matchers:
              - logs_path:
                  logs_path: "/var/log/containers/  "
    output.logstash:
      hosts: ["logstash:5044"]
    logging.level: info
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: filebeat
  name: filebeat-cm2
