apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  ports:
    - name: "5044"
      port: 5044
      targetPort: 5044
  selector:
    io.kompose.service: logstash
