apiVersion: v1
kind: Service
metadata:
  annotations:
    filebeat_enable: "true"
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: order-service
